Fix SQL error due to bad CTE column ordering
We use *, the CTE had talker_alias in the wrong place for the table
spec. Was getting
Error: Tx: ERROR: column "patches" is of type integer[] but expression is of type text (SQLSTATE 42804)